version: '3.7'

services:
  airport-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-14
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run start

  redis_db:
    image: "redis:alpine"
    expose:
      - '6379'